language: node_js
node_js:
  - 10
cache:
  yarn: true
  directories:
  - node_modules
install:
- |
  yarn
script:
  - |
   yarn lint && yarn test
after_success:
  - |
    cat ./test/unit/coverage/lcov.info | ./node_modules/.bin/codecov
